### ISSUE TITLE
ldns-host max domain len

### ISSUE THREAD

**Issue by nuclight** [magv/hypothread#1]
Well, sorry for wrong repo, but seems ldns-host does not have it's own repo, and FreeBSD has bug: https://github.com/NLnetLabs/ldns/issues/137

**Comment by magv** [comment]
Hi. Thanks for reporting, I'll try to fix this. `ldns-host` does have its own repo (see its [web page](https://web.archive.org/web/20180218015519/http://tx97.net/ldns-host/)); it is down at the moment though -- sorry for that. (Normally people just mail me about these sort of things; the mail is in the manual page).
